### ISSUE TITLE
RemoteWebDriverEnricher: Getting UnreachableBrowserException: Error communicating with the remote browser. It may have died.

### ISSUE THREAD

**Issue by testphreak** [RationaleEmotions/talk2grid#1]
## Meta -

Image(s):
node-chrome, node-firefox

Selenium/Image Version:
3.4.0

Docker version:
17.05.0-ce

OS:
Ubuntu 16.04.2 LTS

## Expected Behavior -
Browser session gets initialized correctly and executes the test.

## Actual Behavior -
Appears that RemoteWebDriver instance failed to communicate with the the remote hub due to `java.net.UnknownHostException`

## Info -

Hi @krmahadevan, nice project! 

I tried using Talk2Grid to ease the load on the hub for large installations as you have described [here](https://github.com/RationaleEmotions/talk2grid#how-to-route-all-traffic-directly-to-the-node-for-browser-interactions-). But when the tests run against the grid, I get the error below. As recommended, I have set long timeout values (greater than time taken for 1 test on 1 node) for `cleanUpCycle` and `timeOut`.

It appears that `RemoteWebDriverEnricher` does not work when passing in -host.
```
-host
       <String> IP or hostname : usually determined automatically. Most commonly
       useful in exotic network configurations (e.g. network with VPN)
```

I pass in the host name (-host $HOSTNAME) of the container (node) when adding a node to the grid.

Perhaps Talk2Grid needs to do what Selenium does to figure out the node it wants to route the request to as described [here](https://github.com/SeleniumHQ/selenium/blob/705be71ce9ec7e3825cb1633d3da40ab75a8819f/java/server/src/org/openqa/grid/internal/utils/configuration/GridNodeConfiguration.java#L324-L335)?

Error seen in the test log with Chrome -

```java
May 16, 2017 11:54:56 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
May 16, 2017 11:54:56 AM com.rationaleemotions.RemoteWebDriverEnricher enrichRemoteWebDriverToInteractDirectlyWithNode
INFO: Traffic will now be routed directly to the node.
May 16, 2017 11:54:56 AM com.rationaleemotions.RemoteWebDriverEnricher enrichRemoteWebDriverToInteractDirectlyWithNode
WARNING: ********************************************************************************
Your Hub URL is [http://10.55.197.110:4444/grid/console]
1. It is configured with [300 seconds] as timeout (via -timeout parameter.)
This means that the server automatically kills a session that hasn't had any activity in the last 300 seconds.
2. It is configured with [300 seconds] as cleanup cycle (via -cleanUpCycle parameter.)
This means that the hub will poll for currently running sessions every [300 seconds] to check if there are any 'hung' sessions.
Both these values can cause your test session to be cleaned up and cause test failures.
So please ensure that you set the values for both these parameters on the grid to an appropriately higher value.
********************************************************************************
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'testphreak-MacBook-Pro', ip: 'fe80:0:0:0:6e40:8ff:fea6:a5bc%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_92'
Driver info: driver.version: RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=true, chrome={chromedriverVersion=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5), userDataDir=/tmp/.org.chromium.Chromium.3UHLtt}, takesHeapSnapshot=true, pageLoadStrategy=normal, unhandledPromptBehavior=, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=true, version=58.0.3029.81, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=36ba7ef2-4667-4582-8987-c1da31b1e402, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 36ba7ef2-4667-4582-8987-c1da31b1e402
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:868)
	at com.axiom.turbo.webdriver.util.DriverFactory.openBrowser(DriverFactory.java:110)
	at com.axiom.turbo.webdriver.util.DriverFactory.getNewBrowser(DriverFactory.java:39)
	at com.axiom.turbo.webdriver.listeners.TestListener.onTestStart(TestListener.java:86)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1739)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1714)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:640)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: 1b9f25fb7141: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:139)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:87)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:161)
	at com.rationaleemotions.CustomCommandExecutor.execute(CustomCommandExecutor.java:31)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	... 14 more
```

Tracing through the exception, it executes this [line](https://github.com/RationaleEmotions/talk2grid/blob/master/src/main/java/com/rationaleemotions/CustomCommandExecutor.java#L31) in the code when it fails.

**Comment by krmahadevan** [comment]
@testphreak - Thanks for giving this library a shot.

I am noticing a few anomalies here, so I thought I would get these sorted out with you first.

Your stack trace shows this 

```java
Caused by: java.net.UnknownHostException: 1b9f25fb7141: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
```

AFAIK `1b9f25fb7141` doesn't seem to be a valid representation of an IP address.

Can you please double check on this and let me know if that's correct ?

> Perhaps Talk2Grid needs to do what Selenium does to figure out the node it wants to route the request to as described here?

I doubt if that's the case, because this library makes use of the JSON payload that Selenium sends back when the Grid exposed REST APIs are invoked.

**Comment by testphreak** [comment]
@krmahadevan `1b9f25fb7141` represents the host name of the container/node. As mentioned above, can be either a hostname or IP when starting the selenium server with role node and `-host` options.

The tests run as expected with the default RemoteWebDriver. But when I use `RemoteWebDriverEnricher` I run into this issue. Hence I was wondering if Talk2Grid could adopt a similar node identification logic as the Selenium project.

Most of this logic happens in [BaseRemoteProxy](https://github.com/SeleniumHQ/selenium/blob/138e3ab914e3fb2ac024e5f59251d6cdeae06e0a/java/server/src/org/openqa/grid/internal/BaseRemoteProxy.java).

**Comment by krmahadevan** [comment]
@testphreak 

> Most of this logic happens in BaseRemoteProxy.

Yes I am aware of that part since I have spent a lot of time on the Grid internals.

Here's the predicament that `Talk2Grid` would have.
When `Talk2Grid` queries the Grid with a `sessionId` it gets back a JSON payload. From that payload we extract out the Hostname/IP and then use it to re-route all the traffic directly to it. Since in your case its a hostname (and not a Fully Qualified Domain Name) the client (which is your test that utilizes  `Talk2Grid` ) has difficulties in resolving the hostname/IP.

I would be curious to understand as to why would you be providing the `-host` parameter when starting your node via the docker container ? 

> The tests run as expected with the default RemoteWebDriver. 

Yes that's expected because the Tests are exposed only to the hub and its the hub that is routing the tests to the appropriate node internally.

I am guessing that your Hub and your docker node are on the same machine. Is that correct ? If yes, then have you tried passing the hub's IP address as the value for `-host` parameter ?

Can you please help call out the set of steps that you are following to setup your Grid and node so that I can try and re-produce it ?

**Comment by testphreak** [comment]
Thanks for the explanation @krmahadevan. 

I don't think it's going to be possible to have Talk2Grid talk directly to the nodes in the grid with my setup. My hub and nodes are part of a swarm which may or may not be on the same instance, and it appears that at the time of writing, [there isn't a way](https://github.com/docker/swarm/issues/1106) to get the external IP of the container participating in the swarm.

I like the idea of reducing load on the hub. Will circle back with you when/if we do have the ability to communicate directly to nodes in a swarm from machines not in the swarm.
